COLUMNS:
  Age: int64
  BusinessTravel: object
  DailyRate: int64
  Department: object
  DistanceFromHome: int64
  Education: int64
  EducationField: object
  EmployeeCount: int64
  EmployeeNumber: int64
  EnvironmentSatisfaction: int64
  Gender: object
  HourlyRate: int64
  JobInvolvement: int64
  JobLevel: int64
  JobRole: object
  JobSatisfaction: int64
  MaritalStatus: object
  MonthlyIncome: int64
  MonthlyRate: int64
  YearsSinceLastPromotion: int64
  YearsWithCurrManager: int64

TARGET_COLUMN:
  name: Attrition

